
package Vistas;

import Controladores.ControlMenuPrincipal;
import javax.swing.JFrame;




public class VMenuPrincipal extends javax.swing.JDialog {

   
    ControlMenuPrincipal cmp;
    
    public VMenuPrincipal(ControlMenuPrincipal c) {
        
        initComponents();
        
        cmp = c;
    }

    private VMenuPrincipal(JFrame jFrame, boolean b) {
       
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonTorneo = new javax.swing.JButton();
        botonHistorial = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonBatalla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonTorneo.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        botonTorneo.setText("TORNEO");
        botonTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTorneoActionPerformed(evt);
            }
        });
        getContentPane().add(botonTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 160, 40));

        botonHistorial.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        botonHistorial.setText("HISTORIAL");
        botonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(botonHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, 40));

        botonSalir.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 160, 40));

        botonBatalla.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        botonBatalla.setText("BATALLA");
        botonBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBatallaActionPerformed(evt);
            }
        });
        getContentPane().add(botonBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vistamenuprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTorneoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTorneoActionPerformed

    private void botonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonHistorialActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
          System.exit(0);  
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBatallaActionPerformed
        cmp.confirmarOpcionBatalla();
    }//GEN-LAST:event_botonBatallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VMenuPrincipal dialog = new VMenuPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBatalla;
    private javax.swing.JButton botonHistorial;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTorneo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
