
package Vistas;

import Controladores.ControlRegistro;
import Modelo.ConexionDB;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JButton;





public class VRegistro extends javax.swing.JDialog {

    ConexionDB mdb;
    ControlRegistro cr;
    
    
    /**
     * Creates new form VRegistro
     */
    public VRegistro(ControlRegistro c) {
      
        initComponents();
        
        cr = c; 
    }

    private VRegistro(JFrame jFrame, boolean b) {
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        TextoPass1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextoPass2 = new javax.swing.JTextField();
        TextoUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        botonVolver = new javax.swing.JButton();
        BotonOk = new javax.swing.JButton();
        CheckBoxPNJ = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Engravers MT", 3, 18)); // NOI18N
        jLabel3.setText("cONTRASEÑA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 280, -1));

        TextoPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoPass1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextoPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 250, -1));

        jLabel4.setFont(new java.awt.Font("Engravers MT", 3, 18)); // NOI18N
        jLabel4.setText("JEFE DE TERRENO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 310, -1));

        jLabel5.setFont(new java.awt.Font("Engravers MT", 3, 18)); // NOI18N
        jLabel5.setText("nOMBRE USUARIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));
        getContentPane().add(TextoPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 250, -1));

        TextoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 250, -1));

        jLabel6.setFont(new java.awt.Font("Engravers MT", 3, 18)); // NOI18N
        jLabel6.setText("REPETIR CONTRASEÑA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 310, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 220, -1));

        botonVolver.setFont(new java.awt.Font("Engravers MT", 3, 11)); // NOI18N
        botonVolver.setText("VOLVER");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        BotonOk.setFont(new java.awt.Font("Engravers MT", 3, 11)); // NOI18N
        BotonOk.setText("OK");
        BotonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOkActionPerformed(evt);
            }
        });
        getContentPane().add(BotonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 90, 50));

        CheckBoxPNJ.setText("   PNJ");
        CheckBoxPNJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxPNJActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBoxPNJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vistaregistro.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        cr.volverR();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BotonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOkActionPerformed
        cr.actionPerformed(evt);
       
    }//GEN-LAST:event_BotonOkActionPerformed

    private void CheckBoxPNJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxPNJActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CheckBoxPNJActionPerformed

    private void TextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoUsuarioActionPerformed

    private void TextoPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoPass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VRegistro dialog = new VRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonOk;
    private javax.swing.JCheckBox CheckBoxPNJ;
    private javax.swing.JTextField TextoPass1;
    private javax.swing.JTextField TextoPass2;
    private javax.swing.JTextField TextoUsuario;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

public JButton getBotonConfirmarRegistro(){
    return this.BotonOk;
}

public String getTextoUsuario(){
    String texto = TextoUsuario.getText();
    return texto;
}

public String getContrasena1(){
    String texto = TextoPass1.getText();
    return texto;
}

public String getContrasena2(){
    String texto = TextoPass2.getText();
    return texto;

}

public boolean estadoPNJ(){
        if(CheckBoxPNJ.isSelected() == true){
            return true;
        }else{
            return false;
        }

}
}
